# AddonRepositoryInstall — installs the AddonRepository. Must live in
# vmware-system-vks-public (enforced by the API). See README.
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonRepositoryInstall
metadata:
  name: gvisor-vks
  namespace: vmware-system-vks-public
spec:
  addonRepositoryRef:
    name: gvisor-vks
    namespace: vmware-system-vks-public
