# AddonRepository — HTTPS Helm repo hosting the gvisor-vks chart. See README.
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonRepository
metadata:
  name: gvisor-vks
  namespace: vmware-system-vks-public
  annotations:
    addons.kubernetes.vmware.com/package-offerings: |
      {
        "repositoryVersion": "1.0.0"
      }
spec:
  targetRepositoryName: gvisor-vks   # name of the HelmRepository CR in the VKS clusters
  version: "1.0.0"
  fetch:
    helmRepository:
      url: https://warroyo.github.io/gvisor-vks
  # addonFilters:
  #   - name: gvisor-vks
  #     versions:
  #       - 0.3.0
